version: '2'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 80:8081
  
  db:
    image: percona:5.7.18
    ports:
      - 3306:3306
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: ads
      MYSQL_USER: ads
      MYSQL_PASSWORD: ads
    volumes:
      - ./docker/mysql.cnf:/etc/mysql/conf.d/extra.cnf
      - db:/var/lib/mysql
  pma:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    volumes:
      - ./docker/pma_config.php:/www/config.user.inc.php
    ports:
      - 8082:80

volumes:
  db:
    driver: local
